[package]
name = "transaction-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.1.16"
log = "0.4.17"
env_logger = "0.9.0"
serde = { version = "1.0.137", features = ["derive"] }
rust_decimal = "1.23.1"
csv = "1.1.6"